### ISSUE TITLE
[Bug]: Sandbox crashes Windows 24H2 since the February 2025 security updates

### ISSUE THREAD

**Issue by borque** [microsoft/Windows-Sandbox-Utilities#84]
### Windows Sandbox version

?

### Windows build number

26100.4351

### Other software

Hello!
Since installing the February 2025 security updates for my Win11 24H2, my system has crashed reproducibly every time 60–120 seconds after booting up when the Windows Sandbox is installed.
This happens regardless of whether I am logged in, and whether or not I start a sandbox.

In my Task Manager, I can see two processes called **_vmmemcmSysPrep_** and _**vmmemcmFirstBoot**_ , which consume an ever-increasing amount of memory and CPU time. The fans spin wildly and the whole machine gets hot. After 60–120 seconds, the machine freezes.

Uninstalling the Windows Sandbox feature resolves the problem; re-enabling it causes the problem to reappear.

According to Windows Update, all drivers are up to date.

I found a similar report here: https://github.com/microsoft/Windows-Sandbox/issues/69 .
This report for WSL might also be related: https://github.com/microsoft/WSL/issues/12541 .
Both were closed as 'completed' without comment or resolution.

Further reports relating to laptops from Framework and Lenovo can be found on Reddit and other forums.
For example: https://www.reddit.com/r/techsupport/comments/1hxecip/msi_laptop_locking_up_with_vmmemcmfirstboot_and

Thanks for help!

### Steps to reproduce the bug

See above

### Expected result

A working system with enabled Windows sandbox feature

### Actual result

See above

**Comment by brankoradovanovic-mcom** [comment]
This is precisely the issue I had in the last couple of days, and deactivating Windows Sandbox as suggested above resolved it (go to Turn Windows features on or off -> Windows Sandbox, uncheck and restart). Before that, I tried updating everything through Windows Update and Lenovo Vantage app, but it didn't help.

I have a Lenovo ThinkBook 16 G7 IML Ultra 7 155H laptop - it seems that many people with 155H are experiencing this issue.

**Comment by gadcam** [comment]
If it is the same as https://github.com/microsoft/WSL/issues/12541 probably an `integrated scheduler bug`

**Comment by gex581990** [comment]
I've experiencing this now too. Never been a problem till now. I've literally tried everything. Only thing left it is uninstall my WSL I've worked hard on just to MAYBE get Sandbox to work.

**Comment by kvega005** [comment]
This is an issue with the integrated scheduler that we are working hard to address. It is affecting Windows Sandbox and WSL. The good news is that we have a solution working internally. At the moment, I do not have a date for when the fix will be shipped, but I will update as soon as one is available.

To avoid having the system crash you can stop CmService: `net stop cmservice`. This will kill the vmmemcmSysPrep and vmmemcmFirstBoot processes.

For Microsoft internals: Bug 56225026

**Comment by dickscheel** [comment]
I encounter this in a slightly different way, but I'm guessing that it is the same underlying cause. In my case, I bought a new Windows 11 Pro PC from Dell (Intel Core Ultra 7 265). Windows Sandbox was initially off. I followed the standard steps to add sandbox to the Windows configuration. During the reboot stage of adding sandbox, it reaches 100% and then locks up. I have to do a hard power cycle and then boot into Dell's recovery tools & go back to a recent restore point.

The difference between my case and this GitHub report is that I am initially adding Windows Sandbox rather than working with a PC that previously had the feature working but broke when Windows was updated.

I am running Windows 11 Pro 24H2, build 26100.4652, Windows Feature Experience Pack 1000.26100.128.0

Interestingly, I am able to run Windows Sandbox just fine on my slightly older Dell laptop, which has the same version of Windows (Windows 11 Pro 24H2, build 26100.4652, Windows Feature Experience Pack 1000.26100.128.0). In that case I was already running Windows Sandbox for a long time before 24H2 came out. Probably the main difference is that this PC has an Intel Core i7-10510U CPU.

**Comment by gadcam** [comment]
Not working at Microsoft but it might indeed be linked to the CPU and more specifically to the presence of "performance cores".
From I have seen seem a necessary condition to trigger the bug.

@kvega005 glad to hear that!
Do you now have a timeline for the fix deployment or is it still too early?
Thank you so much!

**Comment by borque** [comment]
@kvega005 : Has the bug perhaps been fixed with the August update (26100.4946)? Or is there any ETA?

**Comment by gex581990** [comment]
> Not working at Microsoft but it might indeed be linked to the CPU and more specifically to the presence of "performance cores". From I have seen seem a necessary condition to trigger the bug.
> 
> [@kvega005](https://github.com/kvega005) glad to hear that! Do you now have a timeline for the fix deployment or is it still too early? Thank you so much!

I have a 11900k, the last monolithic i9 with all normal cores and threads before they started to try the whole e-core and separated IO-die thing. So if it has to do with P and E cores then I shouldn't be experiencing the issue. The only way I was able to fix it myself was to do a clean install of the latest Windows. It somehow got too corrupted for DISM, SFC, or even a "upgrade" quick reinstallation (nor the Fix Windows with Windows Update reinstall option) to fix. I even tried reinstalling Sandbox then manually updating it after erased every existence of it, uninstall, delete temp files, DISM removal, and all that. Nothing would fix it. I think maybe a part of it for me was Bitdefender attacked my Sandbox script I use to run my Sandbox config and when it did that it also took Sandbox with it then after that it was ruined. I've been in talks with Bitdefender about it but they keep saying they are "still investigating"

**Comment by borque** [comment]
According to this post a fix is incoming:
https://github.com/microsoft/WSL/issues/12541#issuecomment-3286263006

**Comment by DaisukeDaisuke** [comment]
Has this bug fix been released to the current stable Windows release as of early October 2025? Or is it being postponed?
This is important to me because this bug prevents me from using windows sandbox

**Comment by dczarnec** [comment]
It seems that in 25H2 (build 26200.6899) the problem is fixed. I have a Lenovo laptop with an Intel Ultra 7 155H, and I had a similar problem. Some time after the 25H2 update, I re-enabled the Sandbox feature, and so far there have been no freezes.

**Comment by pattacini** [comment]
I can confirm that Win Sandbox works flawlessly now also on my system, OS Build 26200.7019.

**Comment by altiris4ever** [comment]
Breaking stuff people uses for work and taking forever to fix is the reason why my hairline is getting thinner every day.

**Comment by Ruchian** [comment]
This issue is still present. I recently removed Windows Sandbox from the Windows Features to avoid it. I had both WSL2 and Sandbox enabled at first, not realizing that was problematic.
I'm not using Sandbox a lot anyway.

Over the year, I noticed the problem slowly got worse, as in, it would take longer and longer before the system would idle. While it was using up resources (through vmmemcmFirstBoot and vmmemcmSysPrep), the SSD's bandwidth would be occupied with 99%. Since this is a bottleneck on my desktop, I could still use my pc, but accessing anything on the system would be slow.

And yeah, it takes about 5~10 minutes before it calmed down, at least currently. 
It used to take less long and I always thought it was Windows Defender or something at first; I never really checked what was causing it to be honest)
Windows Defender does also use up system resources momentarily after a boot, but it may not be related. In any case, it's a problem. You can't even load up a browser with a decent speed when it happens.

Windows Sandbox is a cool feature imo, but I guess Hyper-V could replace it. Since I do want to use Linux Apps and fear it may break the masterboot record if I go Dual OS (+I'd need to shut offSecure Boot and what not to achieve it), I haven't installed linux on my hardware directly as of yet. I suspect uninstalling WSL2 would also make the problem go away, but yeah-

**Comment by kankowski** [comment]
The issue is still present for me, too (Windows 11 Pro 25H2 with all recent updates)

**Comment by huajingyu** [comment]
I have multiple computers, all running Windows 11 25H2.

Some of these computers experience problems enabling Windows Sandbox via "Turn Windows features on or off." The problem is that the progress bar gets stuck during the sandbox activation process (software won't open, the keyboard and mouse become unusable if unplugged and replugged, etc. A forced restart restores it to an disabled state). On another computer, it gets stuck at 57% after restarting (a forced restart at this point will repeatedly cause it to get stuck at 57%. Safe Mode is required to trigger the automatic undo operation). Other computers have no problems.

Even on the problematic computers, installing a second operating system and immediately enabling the sandbox function allows it to be enabled normally without any issues. (At the time, all computers had the same operating system version and the same quality updates.)

**Comment by DaisukeDaisuke** [comment]
You don't need to stubbornly try using Windows Sandbox
By configuring Hyper-V Manager via PS1 + installing with Pro + bypassing the OOBE screen, you'll get a complete copy of Windows
However, you will encounter network slowdowns unless you turn off the Integrated Bridge feature in Device Manager

**Comment by BigBoom20** [comment]
Confirming that this issue is **still not fixed** on the latest stable release as of April 2026.

## Environment

- **OS**: Windows 11 Pro 25H2, Build **26200.8246** (updated today with KB5083769, April 2026 cumulative update)
- **CPU**: 24 logical processors (Intel hybrid P+E core architecture)
- **WSL**: Not enabled

## What Happened

After installing KB5083769, I re-enabled Windows Sandbox via "Turn Windows features on or off." Upon reboot, **`WindowsSandboxRemoteSession.exe` crashed 3 times in a row** (18:04 → 18:06 → 18:07), all with exception code `0xe0434352` (.NET CLR unhandled exception) in `KERNELBASE.dll`.

## Event Log Evidence

```
2026/04/23 18:04:27 - Faulting application: WindowsSandboxRemoteSession.exe, version 0.5.3.0
                       Faulting module: KERNELBASE.dll, version 10.0.26100.8246
                       Exception code: 0xe0434352
(repeated at 18:06:08 and 18:07:02)
```

## Conclusion

The integrated scheduler bug (Bug 56225026, acknowledged by @kvega005 in this thread) is **not resolved** by KB5083769 on Intel hybrid-core hardware. Some users above reported success on Build 26200.6899/7019, but the fix is clearly not universal.

I've had to disable Windows Sandbox again. Would appreciate an update on when a reliable fix will ship.
